apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: card
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "card.sm.apps.ocp.example.com"
