apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-service
spec:
  hosts:
    - user-service
  http:
  - route:
    - destination:
        host: user-service
        port:
          number: 8080