apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: config
spec:
  hosts:
    - "config.sm.apps.ocp1.example.com"
    - "service-config"
  gateways:
    - config
  http:
    - route:
        - destination:
            host: service-config
            port:
              number: 8888
